### ISSUE TITLE
Introduce searchEverywhere.ignorePath that can receive a .gitignore like file

### ISSUE THREAD

**Issue by rdsedmundo** [kbysiec/vscode-search-everywhere#13]
This option would interpret a `.gitignore`-like file and pick all its patterns, taking precedence over `searchEverywhere.exclude`.

**Comment by kbysiec** [comment]
Hi! Thank you for a great idea, sounds really good. I will try to implement it and release it soon.

**Comment by kbysiec** [comment]
Hi,

I have just released the [v.1.1.0](https://github.com/kbysiec/vscode-search-everywhere/tree/v.1.1.0) which contains implemented fetching exclude patterns from gitignore file.

Hope it helps.
Regards,
Kamil
