### ISSUE TITLE
Using in large project impacts performance while typing in source files

### ISSUE THREAD

**Issue by raythurnevoid** [kbysiec/vscode-search-everywhere#14]
After indexing completion the code editor starts to stutter while writing in source files.

Whatever is doing this extension in background maybe it's better to move it in a worker thread if possible?

**Comment by kbysiec** [comment]
Hi, could you provide me with the sample project on GitHub which allows to reproduce the problem? It would be great to investigate the issue.

Thanks.

**Comment by shardul-shah** [comment]
@kbysiec @raythurnevoid  Seconding this, this problem has caused me to uninstall this extension and the performance of VSCode and overall of my machine instantly improved. Might want to optimize this for large projects.

**Comment by kbysiec** [comment]
Thanks guys for pointing this out. Currently I am during tests of the caching mechanism I have implemented to increase the performance during writing in the source files.

I am planning to release the new version in few days so I would be grateful for feedback of it helps somehow.

Regards,
Kamil

**Comment by kbysiec** [comment]
@raythurnevoid, @shardul-shah,

I have just released the new version [v.1.1.0](https://github.com/kbysiec/vscode-search-everywhere/tree/v.1.1.0) which includes the debounce and caching for changes during document editing. Hope it helps.

Could you update, verify and advise if it helps with the performance or the problem still exists?

Thanks for your support!.
Regards,
Kamil

**Comment by shardul-shah** [comment]
@kbysiec I'll take a look later when I can, likely this weekend. Quite busy with work before then. Thanks for your changes and contributions.  I hope the extension is more optimized now.

Best,

Shardul

**Comment by kbysiec** [comment]
@shardul-shah any update on this? 
I have just released new version [v.1.2.0](https://github.com/kbysiec/vscode-search-everywhere/tree/v.1.2.0) with rebuilt tracking changes in workspace which should result in performance increase. Could you verify it?

Regards,
Kamil

**Comment by kbysiec** [comment]
Closed due to inactivity.
