### ISSUE TITLE
Go to symbol sometimes brings me to a "(git) (read-only)" tab.

### ISSUE THREAD

**Issue by MrVPlusOne** [kbysiec/vscode-search-everywhere#15]
Hi, 

I'm using this plugin inside a Julia project. The search functionality has been working great so far and I really like it! However, I noticed that sometimes, after I hit enter to accept some search result,  like shown below
<img width="865" alt="Screen Shot 2021-06-16 at 11 37 12 AM" src="https://user-images.githubusercontent.com/11240361/122259391-c0811280-ce97-11eb-902b-acd6c0ebe595.png">

the plugin would then bring me into a source tab with a  "(git) (read-only)" postfix, which prevents me from editing the file: 
<img width="810" alt="Screen Shot 2021-06-16 at 11 37 29 AM" src="https://user-images.githubusercontent.com/11240361/122259577-f1f9de00-ce97-11eb-903f-43cab9da3338.png">

This only happens to certain symbols I search but not others, and when it happens, it consistently happens for that symbol. Although I haven't figured out a pattern that causes this behavior yet. Do you have any idea how to fix this? This has been quite annoying and made this plugin almost not usable for me.

**Comment by kbysiec** [comment]
Hi,
are you able to create a minimal project and open source it to reproduce the issue? Honestly, I have not met this kind of issue previously, it sounds wired. It needs the investigation for sure.

Regards.

**Comment by MrVPlusOne** [comment]
Hi, sorry for the delay. From some point, this issue just somehow disappeared, so maybe it was caused by some weird configuration on my side. I'm closing this issue.
