### ISSUE TITLE
Result is not displayed long enough

### ISSUE THREAD

**Issue by soulflyman** [kbysiec/vscode-search-everywhere#17]
After typing the symbol I'm looking for, de result is displayed only a realy short time. Not possible to read the hole result or select anything.

I made a gif, and yes it's real time. I hit ctrl+alt+p straight after hitting record and tiped the symbol name.
![Search Everywhere](https://user-images.githubusercontent.com/379492/137320880-7a344d8b-d3c9-430b-baa8-6bd67ca3ef74.gif)

There are 4995 Files and 346478 items indexed in my Workspace.

**Comment by kbysiec** [comment]
Hi apologies for such delay in replying. Does the problem still exist? If yes could you provide me with some demo repo to reproduce it somehow?

I was trying to do so but with no success.

Regards,
Kamil

**Comment by soulflyman** [comment]
Enabled and tested it again. and it works as expected.
