### ISSUE TITLE
Feature idea: List all files included in search

### ISSUE THREAD

**Issue by qpwo** [kbysiec/vscode-search-everywhere#18]
Would be kinda nice to output the full list of files to a tree so I can easily see if there's a mistake in my include/ignore patterns. Could make a temp file and pipe `find . -type f -name $ignorePatterns ! -path  $excludePatterns` or whatever into it. Extension is pretty amazing, basically perfect, as is though.

**Comment by kbysiec** [comment]
Hi,

Apologies for late reply. The feature you requested has been implemented in version 2.0.0. Since this version you can find dedicated output with logs related to any triggered action and scanned directories structure. Hope it helps you somehow.

Regards,
Kamil
