### ISSUE TITLE
What values are allowed in `allowedKinds` and `ignoredKinds`?

### ISSUE THREAD

**Issue by grantmcconnaughey** [kbysiec/vscode-search-everywhere#3]
The `searchEverywhere.itemsFilter` setting has this default value:

```json
{
  "allowedKinds": [],
  "ignoredKinds": [],
  "ignoredNames": []
}
```

What are the possible values for `allowedKinds` and `ignoredKinds`? Thanks!

**Comment by kbysiec** [comment]
Hello! Good question, I forgot to submit the example in readme. Next week I will update the documentation.

You can find the appropriate kind here: https://code.visualstudio.com/api/references/vscode-api#SymbolKind

Hope it helps. In case of any problems or questions, feel free to ask.

**Comment by kbysiec** [comment]
The Readme has been updated. Related version [1.0.4](https://github.com/kbysiec/vscode-search-everywhere/releases/tag/v.1.0.4)

**Comment by grantmcconnaughey** [comment]
Thanks, @kbysiec!

**Comment by kbysiec** [comment]
You're welcome @grantmcconnaughey!
