### ISSUE TITLE
Not displaying result from JS file "background.js"

### ISSUE THREAD

**Issue by tangor86** [kbysiec/vscode-search-everywhere#30]
![image](https://user-images.githubusercontent.com/1785921/160284448-0849147c-870d-4f37-ba1a-6374e5d43464.png)

In the settings, JS file is added:
"searchEverywhere.include": "**/*.{js,html,css,txt}",

I also tried restarting IDE, reload index etc

system:
win10
vscode: 1.65.2
plugin version: v1.2.2

**Comment by kbysiec** [comment]
Hi,

I am not currently in front of computer but based on the screenshot, I think you should search whether 'x' as it is variable name or 'querySelector' as function invoked. The string you pointed in this case is only a input param and I think it is not recognized in the way you think.

Regards,
Kamil

**Comment by tangor86** [comment]
> Hi,
> 
> I am not currently in front of computer but based on the screenshot, I think you should search whether 'x' as it is variable name or 'querySelector' as function invoked. The string you pointed in this case is only a input param and I think it is not recognized in the way you think.
> 
> Regards, Kamil

I think you are right, but is there any way to support also this search?

**Comment by kbysiec** [comment]
Hi,
Apologies for late reply. Currently there are no plans for such a feature. The scan of workspace is done using the built-in API provided by vscode. Currently it doesn't provide such a possibility. Maybe in the future it will change. If so, I will reopen the issue.

Regards,
Kamil

**Comment by kbysiec** [comment]
Duplicate of #28
