### ISSUE TITLE
Feature request: auto-populate selected text in search field and search for it

### ISSUE THREAD

**Issue by tangor86** [kbysiec/vscode-search-everywhere#31]
Sometimes I need to find all occurrences of the word in other files. Usually I copy it and paste in "search in files", but I think some IDEs support clever thing, if you select the word and then trigger the search/popup -> the word is auto-populated and the search is already done... this is much more convenient way to do stuff...

**Comment by kbysiec** [comment]
Hi,

Thank you for proposal. It sounds good to me. I am adding it to the backlog.

Regards,
Kamil

**Comment by mahaker** [comment]
@kbysiec 
Thanks for the great extension!
I'm using it very conveniently.

This FEATURE is the feature I wanted too.
May I implement it?
I would love to contribute.

This is experimental code that I tried in my development environment, worked fine.

```ts
// controller.ts
async function search(): Promise<void> {
  if (controller.shouldIndexOnQuickPickOpen()) {
    clear();
    await workspace.index(ActionTrigger.Search);
  }

  if (controller.shouldLoadDataFromCacheOnQuickPickOpen()) {
    clearConfig();
    !quickPick.isInitialized() && quickPick.init();
    await workspace.removeDataForUnsavedUris();
    controller.setQuickPickData();
  }

  quickPick.isInitialized() && loadItemsAndShowQuickPick();

  // open quickPick with selection
  // it might be natural to write it in the loadItemsAndShowQuickPick function
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showErrorMessage("active text editor not found"); // TODO open quickPick with empty string
    return;
  }

  const { start, end } = editor.selection;
  quickPick.setText(editor.document.getText(new vscode.Range(start, end)));
}
```

**Comment by kbysiec** [comment]
Hi @mahaker,

Thanks you and feel free to contribute. Any pr is highly welcomed. What I could suggest is to make an boolean to switch it in settings  and allow users to decide whether use it or not.

Apologies for late reply.

Regards,
Kamil

**Comment by mahaker** [comment]
Thanks for the reply!

Sounds like it would be nice to be able to set that up!
I'll implement it and send out a pull request.
