### ISSUE TITLE
Please add the README the supported programming languages

### ISSUE THREAD

**Issue by guettli** [kbysiec/vscode-search-everywhere#36]
Please add the README the supported programming languages

I guess only js/ts are supported.

It would be nice to have this for Golang, too.

**Comment by kbysiec** [comment]
Hi @guettli,

The support for other languages is only the matter of configuration. You can override file extensions which should be scanned and... That's it!
In case of any problem, feel free to ask.

Regards,
Kamil

**Comment by guettli** [comment]
Great to hear! Then I would suggest to update the default. Why not include all known extensions. For example: c, cpp, h, py, go, pl, sh, ...

**Comment by kbysiec** [comment]
It is done on purpose. From my perspective I like to have access only to core of my project. This is why it is fully customizable by user to meet it's needs.

Happy I could help.

**Comment by JulindM** [comment]
You are totally right about having access only to the core of the project, but this is an assumption that most project cores are web based cores. 

For the average Joe who just installed this extension and is looking for his, lets say `.cpp` file to test the extension, it would seem as if the extension is broken and is not finding the files he wants and would go right back to uninstalling the extension.

It would be a good idea to have most of the languages supported right out of the gate.
