### ISSUE TITLE
Indexing Not Happening

### ISSUE THREAD

**Issue by artshell** [kbysiec/vscode-search-everywhere#40]
When I tried with the command- Search Everywhere: Reload - I am getting the following toast:
Elapsed time: 0s; Scanned Files:0 Indexed Items: 0

```json
    "searchEverywhere.shouldInitOnStartup": true,
    "searchEverywhere.shouldDisplayNotificationInStatusBar": true,
    "searchEverywhere.shouldHighlightSymbol": true,
    "searchEverywhere.itemsFilter":{
        "allowedKinds": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25],
        "ignoredKinds": [],
        "ignoredNames": []
    },
    "searchEverywhere.include":"**/*.{js,jsx,ts,tsx,java}"
```

search-everywhere version: v2.1.0
platform: mac os

**Comment by kbysiec** [comment]
Hi @artshell,

what language extensions does your project include? It sounds any file doesn't meet the include setting requirements.

Regards,
Kamil

**Comment by artshell** [comment]
@ kbysiec

Just rust program files

**Comment by kbysiec** [comment]
@artshell,

ok, I so you have to update `"searchEverywhere.include":"**/*.{js,jsx,ts,tsx,java}"` setting and include rust file extension (I'll guess it is rs) and it will help. So i would be something like this: `"searchEverywhere.include":"**/*.{js,jsx,ts,tsx,java,rs}"`

**Comment by artshell** [comment]
@kbysiec thanks!

It's ready to work
