### ISSUE TITLE
shift-shift does not work

### ISSUE THREAD

**Issue by guettli** [kbysiec/vscode-search-everywhere#8]
Hi,

I installed the extension, but what now?

I hit shift-shift and nothing happens.

I checked the docs of the plugin. At least at the top there is no hint about how to start "search everywhere".

I guess I am too stupid.

**Comment by kbysiec** [comment]
Hi,

The default shortcut is set to ctrl+alt+p and cmd+alt+p (mac).

Hope it helps.

**Comment by guettli** [comment]
Yes, this helps. Sorry, if I am blind, but wouldn't it be useful to tell this shortcut at the top of the README?

I could not find it here: https://github.com/kbysiec/vscode-search-everywhere

**Comment by kbysiec** [comment]
Great to read it's working. Regarding the readme, you are absolutely right. Thanks for pointing this out. I will update it for sure.

Best regards,
Kamil

**Comment by kbysiec** [comment]
Readme updated in v.1.0.8
